version: '3.8'

services:
  openjob-worker-1:
    build:
      context: ./openjob-spring-boot-samples
      dockerfile: Dockerfile
    image: openjob-spring-boot-samples:latest
    container_name: openjob-worker-1
    extra_hosts:
      - "openjob-server:host-gateway"
    environment:
      - SERVER_PORT=8888
      - SPRING_OPENJOB_ENABLE=true
      - SPRING_OPENJOB_SERVER_ADDRESS=http://host.docker.internal:8088
      - SPRING_OPENJOB_WORKER_APP_NAME=openjob
      - SPRING_OPENJOB_DELAY_ENABLE=true
    ports:
      - "8881:8888"
      - "25588:25588"
  openjob-worker-2:
    build:
      context: ./openjob-spring-boot-samples
      dockerfile: Dockerfile
    image: openjob-spring-boot-samples:latest
    container_name: openjob-worker-2
    extra_hosts:
      - "openjob-server:host-gateway"
    environment:
      - SERVER_PORT=8888
      - SPRING_OPENJOB_ENABLE=true
      - SPRING_OPENJOB_SERVER_ADDRESS=http://host.docker.internal:8088
      - SPRING_OPENJOB_WORKER_APP_NAME=openjob
      - SPRING_OPENJOB_DELAY_ENABLE=true
    ports:
      - "8882:8888"
      - "25589:25588"
